kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: csi.trident.netapp.io
  finalizers:
  - kubernetes.io/pvc-protection
  name: {{ .Values.dataloadjob.dataload_pvc_name }}
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.dataloadjob.dataload_pvc_size }}
  storageClassName: netapp-file-standard
  volumeMode: Filesystem
