apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      imagePullSecrets:
        - name: {{ .Values.artifactory_secret_name }}
      volumes:
      - name: demojob-volume
        persistentVolumeClaim:
          claimName: {{ .Values.demojob.demojob_pvc_name }}
      containers:
      - name: demogdal
        image: >-
          artifacts.developer.gov.bc.ca/docker-remote/osgeo/gdal:alpine-normal-3.4.1
        #Calling the shell script that was pulled by the init container
        # link to article showing how to call multiple commands in single
        # call: https://stackoverflow.com/questions/33979501/kubernetes-passing-multiple-commands-to-the-container
        command: ["sh",  "sleep 6000"]
        volumeMounts:
        - name: demojob-volume
          mountPath: /data
      initContainers:
      - name: config-data
        image: >-
          artifacts.developer.gov.bc.ca/docker-remote/curlimages/curl:7.81.0
        #docker pull busybox:1.35.0
        #  artifacts.developer.gov.bc.ca/docker-remote/alpine/git:v2.32.0
        command: ["curl","https://raw.githubusercontent.com/bcgov/nr-water-notations/main/jobs/demogdal.sh","-o","/data/demogdal.sh"]
        #command: ["ls","/data"]
        volumeMounts:
        - name: demojob-volume
          mountPath: /data
      restartPolicy: Never